.PHONY : h
h :
	latex wsHyp.tex; dvips -o wsHyp.ps wsHyp.dvi; ps2pdf wsHyp.ps

.PHONY : hh
hh :
	latex wsHyp2.tex; dvips -o wsHyp2.ps wsHyp2.dvi; ps2pdf wsHyp2.ps

.PHONY : hhh
hhh :
	latex wsHyp3.tex; dvips -o wsHyp3.ps wsHyp3.dvi; ps2pdf wsHyp3.ps

.PHONY : x
x :
	latex wsChi2.tex; dvips -o wsChi2.ps wsChi2.dvi; ps2pdf wsChi2.ps

.PHONY : xx
xx :
	latex wsChi2b.tex; dvips -o wsChi2b.ps wsChi2b.dvi; ps2pdf wsChi2b.ps

.PHONY : q
q :
	latex quizHyp.tex; dvips -o quizHyp.ps quizHyp.dvi; ps2pdf quizHyp.ps

.PHONY : clean
clean :
	rm *.log *.dvi *.aux *.out *~ *.ps
