.PHONY : qn
qn :
	latex quiz_normal.tex; dvips -o quiz_normal.ps quiz_normal.dvi;
	ps2pdf quiz_normal.ps

.PHONY : qms
qms :
	latex quiz_mean_sd.tex; dvips -o quiz_mean_sd.ps quiz_mean_sd.dvi;
	ps2pdf quiz_mean_sd.ps

.PHONY : qzr
qzr :
	latex quiz_z_cor.tex; dvips -o quiz_z_cor.ps quiz_z_cor.dvi;
	ps2pdf quiz_z_cor.ps

.PHONY : ttt
ttt :
	latex text3.tex; dvips -o text3.ps text3.dvi; ps2pdf text3.ps

.PHONY : tttt
tttt :
	latex text4.tex; dvips -o text4.ps text4.dvi; ps2pdf text4.ps

.PHONY : t5
t5 :
	latex text5.tex; dvips -o text5.ps text5.dvi; ps2pdf text5.ps

.PHONY : i
i :
	latex ws_descr1.tex; dvips -o ws_descr1.ps ws_descr1.dvi; ps2pdf ws_descr1.ps

.PHONY : q
q :
	latex ws_quant.tex; dvips -o ws_quant.ps ws_quant.dvi;
	ps2pdf ws_quant.ps

.PHONY : v
v :
	latex ws_vars.tex; dvips -o ws_vars.ps ws_vars.dvi;
	ps2pdf ws_vars.ps

.PHONY : b
b :
	latex ws_Rbar1.tex; dvips -o ws_Rbar1.ps ws_Rbar1.dvi;
	ps2pdf ws_Rbar1.ps

.PHONY : bb
bb :
	latex ws_Rbar2b.tex; dvips -o ws_Rbar2b.ps ws_Rbar2b.dvi;
	ps2pdf ws_Rbar2b.ps

.PHONY : ms
ms :
	latex wup_meansd.tex; dvips -o wup_meansd.ps wup_meansd.dvi;
	ps2pdf wup_meansd.ps

.PHONY : qm
qm :
	latex quiz_center.tex; dvips -o quiz_center.ps quiz_center.dvi;
	ps2pdf quiz_center.ps

.PHONY : s
s :
	latex ws_sd1.tex; dvips -o ws_sd1.ps ws_sd1.dvi; ps2pdf ws_sd1.ps

.PHONY : rm
rm :
	latex ws_Rmean.tex; dvips -o ws_Rmean.ps ws_Rmean.dvi;
	ps2pdf ws_Rmean.ps

.PHONY : no
no :
	latex ws_NHANESIII0.tex; dvips -o ws_NHANESIII0.ps ws_NHANESIII0.dvi;
	ps2pdf ws_NHANESIII0.ps

.PHONY : nh
nh :
	latex ws_NHANESIIIa.tex; dvips -o ws_NHANESIIIa.ps ws_NHANESIIIa.dvi;
	ps2pdf ws_NHANESIIIa.ps


.PHONY : r
r :
	latex ws_NHANESIIIb.tex; dvips -o ws_NHANESIIIb.ps ws_NHANESIIIb.dvi;
	ps2pdf ws_NHANESIIIb.ps

.PHONY : rr
rr :
	latex ws_NHANESIIIc.tex; dvips -o ws_NHANESIIIc.ps ws_NHANESIIIc.dvi;
	ps2pdf ws_NHANESIIIc.ps

.PHONY : h
h :
	latex ws_histA.tex; dvips -o ws_histA.ps ws_histA.dvi
	ps2pdf ws_histA.ps

.PHONY : a
a :
	latex ws_area1.tex; dvips -o ws_area1.ps ws_area1.dvi; ps2pdf ws_area1.ps

.PHONY : clean
clean :
	rm *.log *.dvi *.ps *.aux *.out *~
